# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "xhci_pci" "nvme" "ahci" "usbhid" "usb_storage" "sd_mod" "vfat" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];


  #LUKS device Configuration
  boot.initrd.luks.devices = {
   cryptswap = { 
    device = "/dev/disk/by-partuuid/3d8ccd69-9e4a-4dfb-a3b4-184ea898ab2e"; 
    crypttabExtraOpts = [ "tpm2-device=auto" ];
   };
   cryptroot = { 
    device = "/dev/disk/by-partuuid/b9281186-32e6-4222-8b38-862f85b7fb41"; 
    crypttabExtraOpts = [ "tpm2-device=auto" ];
   };
   cryptvarlog = { 
    device = "/dev/disk/by-partuuid/c06274d9-dda7-49ab-aff0-d3bdddee4fe7"; 
    crypttabExtraOpts = [ "tpm2-device=auto" ];
   };
   crypthome = { 
    device = "/dev/disk/by-partuuid/35e2d735-f23e-40e7-aaf3-8f17f1ff27ac"; 
    crypttabExtraOpts = [ "tpm2-device=auto" ];
   };
  };
   

  #Filesystem Mapping
  fileSystems = {
   "/" = {
    device = "/dev/disk/by-uuid/79b1c6ba-3f47-4a7d-9606-8d132a3af605";
    fsType = "btrfs";
    options = [ "compress=zstd" ];
   };

  "/home" = {
    device = "/dev/disk/by-uuid/04955565-4c8c-4b27-87fe-0b2efa74669c";
    fsType = "btrfs";
    options = [ "compress=zstd" ];
   };

  "/var/log" = {
    device = "/dev/disk/by-uuid/b6366e5f-510e-41e7-b6ef-72ba6ce27a10";
    fsType = "btrfs";
    options = [ "compress=zstd" ];
   };

  "/boot" = {
    device = "/dev/disk/by-partuuid/8a8a1264-36de-4775-b39e-fc96a8c57dd1";
    fsType = "vfat";
    options = [ "umask=0077" ];
   };
  };


  swapDevices = [
   { device = "/dev/disk/by-uuid/0f717216-ff39-424a-9825-17aae5d14c85"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
